### PR TITLE
try make decoding and decoding correct with amqp specification

### PR DESCRIPTION
**Pull request by michal800106**
We recently in our product have met a problem that sender and publisher written in different languages couldn't communicate through rabbitmq. The problem is that different libraries have a different implementation of amqp spec and encoding/decoding is incorrect.

from amqp spec types should set as below:

 field-value         =
 'A' field-array
 'D' decimal-value
 'F' field-table
 'I' long-int
 'S' long-string
 'T' timestamp
 'V' ; no f
 'b' short-short-int
 'd' double
 'f' float
 'l' long-long-uint
 's' short-string
 't' boolean
 'B' short-short-uint
 'U' short-int
 'u' short-uint
 'i' long-uint
 'L' long-long-int

### CODE REVIEW

**Comment by gmr** [comment]
This library is very focused on strict spec interpretation with RabbitMQ enhancements. I'm will double-check the behaviors against your MR.

**Comment by gmr** [comment]
Did you compare the AMQP spec with the RabbitMQ Errata for field behaviors?

**Comment by michal800106** [comment]
No, I will check it. The problem in our program started with switch to newer version of aiormq==4.0.0 which bumped version of pamqp. I've checked tables of types in other rabbitmq's libraries used by us (streadway/amqp and lapin). For streadway we also make PR with fix because there was no implementation for B (https://github.com/streadway/amqp/pull/494). Lapin in our opinion has the most complete set of protocol types: https://github.com/CleverCloud/amq-protocol/blob/master/types/src/types.rs#L59.
After making this PR we discovered that in different version of rabbitmq is different behavior so you have right that I should check again this PR.

**Comment by michal800106** [comment]
I've checked it with errata and I've made fix in PR. I believe that now is correct with errata

**Pull request merged**
