### PR TITLE
specification: only warns instead of raise DeprecationWarning

### PR DESCRIPTION
**Pull request by dzen**
Updates codegen tool to mention the method as deprecated,
instead of hardly raise a DeprecationWarning

### CODE REVIEW

**Comment by michaelklishin** [comment]
@gmr this makes sense to me. I don't think any other client straight raises an error, although we may start doing that closer to the 4.0 release.

**Comment by dzen** [comment]
@michaelklishin a 4.0 release ? I only see a 2.0 release

**Comment by michaelklishin** [comment]
Sorry, I meant RabbitMQ 4.0 and what is going to happen (but hasn't yet) in a few clients developed by our team ;)

I think it's a sensible change for now.

**Comment by gmr** [comment]
LGTM :) Thanks, will release a new version today.

**Pull request merged**
